version: "3"

services:
#--------Api Server -----
  api-server:
    container_name: "api-server"
    restart: always
    build:
      context: ./api-server
      dockerfile: api-server.Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - CHOKIDAR_USEPOLLING="true"
    working_dir: /app
    ports:
      - 5001:5001
    networks:
      - app_network
#--------Redis -----
  redis:
    container_name: "redis"
    image: redis:alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - app_network
#--------DB -----
  db:
    container_name: "database"
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    command: --init-file /init_scripts/init_db.sql
    volumes:
      - db_data:/var/lib/mysql
      - init_scripts:/init_scripts
    networks:
      - app_network
#--------client -----
  client:
    container_name: "client"
    build:
      context: ./client #Contexto/directorio donde está el dockerfile para la construcción de la imagen
      dockerfile: Dockerfile #nombre del dockerfile para crear la imagen
    networks: # red(es) a la(s) que pertenecerá el contenedor
      - web_network
      - app_network
    environment: # variables de entorno, utilizadas para la configuración del contenedor
      - NODE_ENV=development
#--------nginx -----
  nginx:
    container_name: "proxy"
    build:
      context: ./nginx #Contexto/directorio donde está el dockerfile para la construcción de la imagen
      dockerfile: Dockerfile
    ports: #Puertos externo que se utilizará para el contenedor
      - '8080:80'
    volumes:
      - nginx_default:/etc/nginx/conf.d/default.conf:ro
    networks: # red(es) a la(s) que pertenecerá el contenedor
      - web_network
#-------------
volumes:
  db_data:
  redis_data:
  init_scripts:
  nginx_default:
networks:
  app_network:
    driver: bridge
  web_network:
    driver: bridge
